def sample_field_mapper(sample_field: str):
    match sample_field:
        case "ESTAB_UPRN":
            return "estabUprn"
        case "UPRN":
            return "uprn"
        case "ADDRESS_LEVEL":
            return "addressLevel"
        case "ADDRESS_LINE1":
            return "addressLine1"
        case "ADDRESS_LINE2":
            return "addressLine2"
        case "ADDRESS_LINE3":
            return "addressLine3"
        case "POSTCODE":
            return "postcode"
        case "TOWN_NAME":
            return "townName"
        case _:
            return sample_field
